# Generated by Django 5.1 on 2024-08-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
