# Generated by Django 5.1 on 2024-08-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('django', 'Django'), ('database', 'Database'), ('debugging', 'Debugging')], max_length=30, null=True),
        ),
    ]
