# Generated by Django 5.1 on 2024-08-18 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('bootcamp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_bootcamps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bootcamp.bootcamps'),
        ),
    ]
