# Generated by Django 5.1 on 2024-08-18 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('bootcamp', '0002_remove_bootcamps_students_bootcamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_bootcamps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bootcamp.bootcamp'),
        ),
    ]
