# Generated by Django 5.1 on 2024-08-20 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_city_alter_user_kod_meli_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_bootcamps',
        ),
    ]
