# Generated by Django 5.1 on 2024-08-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_user_bootcamps'),
        ('bootcamp', '0006_remove_bootcamp_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bootcamp',
            field=models.ManyToManyField(blank=True, null=True, to='bootcamp.bootcamp'),
        ),
    ]
