# Generated by Django 5.1 on 2024-08-18 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_user_bootcamps'),
        ('bootcamp', '0002_remove_bootcamps_students_bootcamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bootcamps',
        ),
    ]
