# Generated by Django 5.1 on 2024-08-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_user_bootcamps'),
        ('bootcamp', '0004_comment_for_bootcamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bootcamp',
            name='students',
        ),
        migrations.AddField(
            model_name='bootcamp',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.user'),
        ),
    ]
