# Generated by Django 5.1 on 2024-08-20 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0005_remove_bootcamp_students_bootcamp_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bootcamp',
            name='students',
        ),
    ]
