# Generated by Django 5.1 on 2024-08-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0006_remove_bootcamp_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_for_bootcamp',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
