# Generated by Django 5.1 on 2024-08-21 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('bootcamps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boot', to='learning.bootcamp')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cls', to='learning.class')),
            ],
        ),
    ]
